version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command:
              pip install --upgrade pip;
              pip install -r requirements.txt;
      - run:
          name: "Lint code"
          command:
              flake8 --max-line-length 99 openai_dm/;
      # - run:
      #     name: "Execute Tests"
      #     command:
      #         python -m unittest

workflows:
  build_and_test:
    jobs:
      - build
